### PR TITLE
Feature/adding dart support

### PR DESCRIPTION
**Pull request by stefaniereuter**
This is related to ECC-1922 , to add support for Fesom grid DART . This is relevant for intermediate climate DT runs with FESOM.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/eccodes?pullRequest=246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/eccodes?pullRequest=246) before we can accept your contribution.<br/><hr/>**Stefanie Reuter** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/eccodes?pullRequest=246) it.</sub>

**Comment by stefaniereuter** [comment]
I initially thought that C and N stands for Core2 and NG5 in subgridType but I then found a comment from Willem that it actually stands for centroids and edges i.e. the second commit that removes the D

**Comment by shahramn** [comment]
@stefaniereuter  You need to sign the CLA (Contributor License Agreement) before we can proceed.
Vielen Dank

**Comment by dsarmany** [comment]
> I initially thought that C and N stands for Core2 and NG5 in subgridType but I then found a comment from Willem that it actually stands for centroids and edges i.e. the second commit that removes the D

Yes, that is correct. So the combined changes in this PR are fine. It will be probably be worth squashing them into a single commit at the point of merging it.

**Review by dsarmany — APPROVED** [review]

**Comment by stefaniereuter** [comment]
Hi Sharam, sorry I had already signed it but I did not click on rechecking. For me it now says all committers signed... So I assume it worked

**Comment by shahramn** [comment]
The last three entries in this table should be prefixed by a string like FESOM
e.g.,
```
'FESOM_CORE2' = { numberOfGridUsed = 8; }
'FESOM_NG5'   = { numberOfGridUsed = 9; }
'FESOM_DART' =  { numberOfGridUsed = 10; }
```
Really this kind of naming should be the responsibility of Data Governance

**Comment by stefaniereuter** [comment]
I've just contacted Data Governance. I'll create a ticket in their jira space and will let you know what they say.

**Review by mjg41 — APPROVED** [review]
Hi,
From discussions with @wdeconinck and his [confluence page](https://confluence.ecmwf.int/display/~nawd/atlas-fesom) that you linked above, all those new ocean grids are handcrafted for the FESOM ocean model by the AWI developers. Therefore I'd be happy with leaving them as they are with no additional changes to be honest. Ultimately this is only a concept helper key which is in our local definitions in any case, and the number is the key fixed piece of metadata.
So now DGOV approved, thanks for bringing it to our attention!

**Comment by shahramn** [comment]
We have a metkit test failure (metkit_test_codes_decoder). I have asked @danovaro to fix it. Once that is done, I will merge this PR

**Pull request merged**
