### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by ReallyNiceGuy**
The field grib_samples_path from grib_context was being left in an
  inconsistent state, either with static memory or with heap allocated memory,
  depending on the existence of the env var ECCODES_SAMPLES_PATH and
  the preprocessor variable ECCODES_SAMPLES_PATH.

Free the memory allocated for grib_samples_path and grib_definition_files_path
  when setting them from the API calls.

### CODE REVIEW

**Comment by ReallyNiceGuy** [comment]
I am sorry, what am I supposed to do now?

**Comment by shahramn** [comment]
Thank you for your pull request. We have some issues with the continuous integration and I will look into them.
Please bear with me.

**Comment by shahramn** [comment]
Can you please rebase your branch with the latest develop?

**Comment by ReallyNiceGuy** [comment]
Done

**Pull request closed without merging**
