### PR TITLE
Fetch ecbuild if not downloaded before

### PR DESCRIPTION
**Pull request by foxtran**
This patch makes possible to clone and build this repo without additional download steps

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/eccodes?pullRequest=241) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/eccodes?pullRequest=241) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/eccodes?pullRequest=241) it.</sub>

**Comment by shahramn** [comment]
Thank you. But I spotted a problem
Building ecCodes works fine but when you run the tests, many fail. Specifically those of ecbuild itself

**Comment by shahramn** [comment]
One solution would be to suppress or disable the tests of ecbuild in this case. Normally one can do this by:
`cmake /path/to/git/ecbuild -D ENABLE_TESTS=0`

**Comment by foxtran** [comment]
@shahramn, thank you! I've fixed issue with tests. 
```
100% tests passed, 0 tests failed out of 98

Label Time Summary:
eccodes       = 102.18 sec*proc (98 tests)
executable    =   0.11 sec*proc (1 test)
sanity        = 102.07 sec*proc (97 tests)
script        = 102.07 sec*proc (97 tests)
```

**Comment by shahramn** [comment]
A couple of points:
When I run this on my MacBook with cmake 3.30.3, I get this warning:
```
-- Fetching ecbuild...
CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(ecbuild) is deprecated, call
  FetchContent_MakeAvailable(ecbuild) instead.  Policy CMP0169 can be set to
  OLD to allow FetchContent_Populate(ecbuild) to be called directly for now,
  but the ability to call it with declared details will be removed completely
  in a future version.
Call Stack (most recent call first):
  CMakeLists.txt:31 (FetchContent_Populate)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by foxtran** [comment]
@shahramn, the warning should disappear now :)

**Comment by shahramn** [comment]
It looks a lot better now. The messages are much more informative:
```
-- Could NOT find ecbuild (missing: ecbuild_DIR)
-- Fetching ecbuild...
-- Populating ecbuild
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/bld/ecbuild-subbuild
[ 11%] Creating directories for 'ecbuild-populate'
[ 22%] Performing download step (git clone) for 'ecbuild-populate'
Cloning into 'ecbuild-src'...
HEAD is now at a07c0a5 Merge branch 'hotfix/3.8.5'
[ 33%] Performing update step for 'ecbuild-populate'
-- Fetching latest from the remote origin
HEAD is now at a07c0a5 Merge branch 'hotfix/3.8.5'
[ 44%] No patch step for 'ecbuild-populate'
[ 55%] No configure step for 'ecbuild-populate'
[ 66%] No build step for 'ecbuild-populate'
[ 77%] No install step for 'ecbuild-populate'
[ 88%] No test step for 'ecbuild-populate'
[100%] Completed 'ecbuild-populate'
[100%] Built target ecbuild-populate
```

**Comment by shahramn** [comment]
Thank you so much

**Pull request merged**
