### PR TITLE
Set invalid values to 0 in RLE

### PR DESCRIPTION
**Pull request by jfsimoneau**

### CODE REVIEW

**Comment by shahramn** [comment]
Many thanks. I have now merged it to "develop".

**Comment by jfsimoneau** [comment]
Thank you very much!

**Comment by shahramn** [comment]
You are very welcome and if you do come across some more GRIB data with this packing type, please do let me know

**Comment by noritada** [comment]
Sorry to interrupt from the side. I think it would be nice if `levels[0]` is treated as a missing value instead of 0.
wgrib2 outputs a missing value for a grid point with level 0, as shown below:

```shellsession
% ./install/bin/grib_get_data -w count=1 Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin | head -5
Latitude Longitude Value
   47.958  118.062 0.0000000000e+00
   47.958  118.188 0.0000000000e+00
   47.958  118.312 0.0000000000e+00
   47.958  118.438 0.0000000000e+00
%  wgrib2 -d 1.1 -order raw -text - Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin | head -5
1.1:09.999e+20
9.999e+20
9.999e+20
9.999e+20
9.999e+20
```

However, when I tried to revert the change in this PR, the missing values are hard-coded and remained the same value even with the `-m` option, probably because those missing values are not represented in the bitmap. So it seems that simply reverting this change is not enough.

```shellsession
%  ./install/bin/grib_get_data -w count=1 Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin | head -5 
Latitude Longitude Value
   47.958  118.062 -1.0000000000e+100
   47.958  118.188 -1.0000000000e+100
   47.958  118.312 -1.0000000000e+100
   47.958  118.438 -1.0000000000e+100
%  ./install/bin/grib_get_data -m 9999 -w count=1 Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin | head -5
Latitude Longitude Value
   47.958  118.062 -1.0000000000e+100
   47.958  118.188 -1.0000000000e+100
   47.958  118.312 -1.0000000000e+100
   47.958  118.438 -1.0000000000e+100
```

(There is another reason why it would be better if `levels[0]` is treated as a missing value. In JMA SAR GPV, level 1 = 0mm/h, and level 0 needs be distinguishable from it.)

**Comment by shahramn** [comment]
I am doing some more work on this to ensure that the statistics keys "min", "max" and "average" match what wgrib2 reports:
```
% f=Z__C_RJTD_20210817090000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin
% wgrib2 -stats $f
mean=1.00303  min=1  max=3
mean=1.00228  min=1  max=3
mean=1.00173  min=1  max=3
mean=1.00111  min=1  max=3
mean=1.00077  min=1  max=2
mean=1.00014  min=1  max=2
mean=1        min=1  max=1

% grib_ls -p average,min,max $f
avg         min         max         
1.00303     1           3          
1.00228     1           3          
1.00173     1           3          
1.00111     1           3          
1.00077     1           2          
1.00014     1           2          
1           1           1          
```

**Comment by noritada** [comment]
With my local build, I have checked that missing values specified with level 0 in template 5.200 can be handled properly.
Many thanks!

**Comment by shahramn** [comment]
In the next release of ecCodes (v2.30.0) all known issues with decoding grid_run_length packing are fixed.

**Comment by jfsimoneau** [comment]
That is fantastic, thank you @shahramn! I'm quite pleased with this news, I was not able to fix it myself.

**Comment by shahramn** [comment]
I also fixed the number of missing values (undefined) reported. So now it matches wgrib2

````
% f=Z__C_RJTD_20210817090000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin 

% wgrib2 -stats $f
1.1:0:ndata=86016:undef=71493:mean=1.00303:min=1:max=3:cos_wt_mean=1.00303
1.2:0:ndata=86016:undef=71558:mean=1.00228:min=1:max=3:cos_wt_mean=1.00228

> grib_ls -p numberOfDataPoints,numberOfMissing $f
numberOfDataPoints  numberOfMissing
86016               71493
86016               71558
```

**Pull request merged**
