### PR TITLE
We have new adaptions for the NEC HPC.

### PR DESCRIPTION
**Pull request by schickj**

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=26) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=26) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eccodes?pullRequest=26) it.</sub>

**Comment by schickj** [comment]
We made changes especially in grib_encode_double_array.

**Comment by shahramn** [comment]
Please sign the Contributor License Agreement. Thank you

**Comment by schickj** [comment]
Hi, Shahramn is it O.K. or have I to do some other things?

**Comment by shahramn** [comment]
> Hi, Shahramn is it O.K. or have I to do some other things?
Dear Johannes, thanks for signing the CLA. Actually we do not have an NEC machine so cannot test these changes at all.
Can you tell us what tests you have performed?

**Comment by schickj** [comment]
Hi Shahramn, I hope, you and your family and friends are not effected by this crisis. NEC made a DACE-Test. The performance will be much better with EcCodes and the vectorization will be much better with this changes.

**Comment by shahramn** [comment]
Thank you so much dear Johannes. I too wish you and your family health :)

**Comment by schickj** [comment]
I updated the file and edited the ISSUE SUP-3134.

**Pull request merged**
