### PR TITLE
To read run length compressed data

### PR DESCRIPTION
**Pull request by jfsimoneau**
This is a rework of Tatsuya Noyori's PR #70. With his authorization, I am submitting it here without the public domain requirements after testing on real JMA data.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=72) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=72) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eccodes?pullRequest=72) it.</sub>

**Comment by shahramn** [comment]
Thank you
Can you please sign our [Contributor License Agreement](http://claassistant.ecmwf.int/ecmwf/eccodes?pullRequest=72) before we can accept your contribution

**Comment by jfsimoneau** [comment]
> Thank you Can you please sign our [Contributor License Agreement](http://claassistant.ecmwf.int/ecmwf/eccodes?pullRequest=72) before we can accept your contribution

I did. I'm not sure why it doesn't show.

**Comment by jfsimoneau** [comment]
Figured it out. Noyori-san was sill an author, so I edited the history to list only myself.

**Comment by shahramn** [comment]
Dear @jfsimoneau 
I have merged this into a branch for further testing.
I came across several issues:
First of all I tried running wgrib2 on the data files provided in PR#70
i.e., http://www.jmbsc-west.jp/jp/online/online-sample/NOWC_GPV_Ggis1km/NOWC_GPV_Ggis1km_Prr05lv.zip

When I get the min and max values from ecCodes, they do not agree with wgrib2
For example I extracted the first message in
NOWC_GPV_Ggis1km_Prr05lv/Z__C_RJTD_20170807032000_NOWC_GPV_Ggis1km_Prr05lv_FH0005-0100_grib2.bin

via
```
% grib_copy -wcount=1 NOWC_GPV_Ggis1km_Prr05lv/Z__C_RJTD_20170807032000_NOWC_GPV_Ggis1km_Prr05lv_FH0005-0100_grib2.bin rle.msg01.grib2
```

Running wgrib2 -stats prints:
```
% wgrib2 -stats rle.msg01.grib2 
check_pdt_size: pdt=50008 needs to be added to pdt_len(..)
1:0:ndata=8601600:undef=6259785:mean=0.701772:min=0:max=201:cos_wt_mean=0.722284
```

whereas ecCodes does:
```
% grib_ls -n statistics rle.msg01.grib2
max         min         avg           sd          skew        kurt        const
201         -1e+100     -7.27747e+99  4.4512e+99  1.02331     nan         0
```
So the minimum is incorrect.

**Comment by jfsimoneau** [comment]
Thank you for the comments. I will look into that.

I noticed the -1e+100 values too. I'll take a look at the source and the standard to make sure it fits.

**Comment by jfsimoneau** [comment]
Ok, the code in this PR converts the invalid values to `GRIB_MISSING_DOUBLE` instead of 0 as wgrib2 does. I will see if we can mark those values as missing directly.

**Comment by shahramn** [comment]
One other thing:
I cannot include the file

template.4.50008.def

in our definitions as that is a local product definition number. We can use it just for testing that GRIB data from Japan.

**Comment by jfsimoneau** [comment]
I don't know of any, unfortunately. I can always try to generate one, but I'm not an expert on the matter.

Q. right back at you: If I were to need the template.4.50008.def file locally, how would I install it so ecCodes would be able to use it?

**Comment by shahramn** [comment]
Dear @jfsimoneau 
The way ecCodes finds various definition files/tables is similar to how UNIX finds executable in its PATH environment variable.
So the steps are as follows:

```
mkdir -p mydefs/grib2
cp /path/to/src/template.4.50008.def mydefs/grib2
export ECCODES_DEFINITION_PATH=$PWD/mydefs/grib2
```
Now the tools like grib_ls, grib_dump should work

**Comment by jfsimoneau** [comment]
Thank you for your answers @shahramn!

All in all, I think we can simply drop the template.4.50008.def file from this PR since we will pick it up on our side. For the minimum value of -1e100, I don't think it's wrong, since wgrib2 was not right by saying it was a value of 0. It is an invalid (missing) value encoded inside the RLE stream. I have not found a way to tell ecCodes the value is missing without a bitmap.

Is there anything else I can do to help?

**Comment by shahramn** [comment]
I would like to get the same answers as wgrib2. Even if you think they're doing the 'wrong' thing.

**Comment by jfsimoneau** [comment]
Very well, will do!

**Comment by jfsimoneau** [comment]
Made new PR: https://github.com/ecmwf/eccodes/pull/73

**Pull request merged**
