### PR TITLE
Improvement on file spliting

### PR DESCRIPTION
**Pull request by wqu-bom**
Allow an input file to be split into each individual message (if nchunk=-1)

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:5000/ecmwf/eccodes?pullRequest=16) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:5000/ecmwf/eccodes?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:5000/check/ecmwf/eccodes?pullRequest=16) it.</sub>

**Comment by shahramn** [comment]
Thank you. Have you included tests?

**Comment by shahramn** [comment]
Thank you for the test. By the way have you signed the Contributor License Agreement?

**Comment by dtip** [comment]
Hi chaps. Can I suggest you switch the osx_image in .travis.yml to xcode10.2? That may fix the MacOS build issue.

**Comment by shahramn** [comment]
Thanks Daniel. I will change it and push to develop

**Comment by wqu-bom** [comment]
I have not signed the CLA. I have tried a few links and it did not work. Please advise how to or email me a form that I can sign and send back to you. Thanks.

**Comment by StephanSiemen** [comment]
Hi @wqu-bom,
I signed the code agreement fine (see comment above). The system uses email addresses to identify users and contributions. The system relies on you using the same email address for the GIT checkins and the GitHub account. Could you please check you use the same email?

Do you see the agreement and able to sign it?
Thanks

**Comment by wqu-bom** [comment]
Tried the "CLA not signed yet" button, but it did not work (error msg below), nor the link "Details" above.
Description: internal error - server connection terminated

**Comment by jameshawkes** [comment]
Hi @wqu-bom, our bot was probably blocked by a firewall somewhere causing the error you received above -- although I could not replicate it. The bot is now on listening on port 80 so it should be accessible.

If you wouldn't mind, please try again at this link:
http://claassistant.ecmwf.int/ecmwf/eccodes?pullRequest=16

Thanks!

**Comment by wqu-bom** [comment]
Hi @jameshawkes, I followed the link, but it seems that it has not gone through fully. I got the following (attached).

**Comment by jameshawkes** [comment]
Hi @wqu-bom, instead of an attachment I got a copy of the email notification on Github. Can you upload it directly on the Github PR instead of via email?

(You can attach files in the reply box at the bottom)
https://github.com/ecmwf/eccodes/pull/16

Otherwise just send me the attachment at James.Hawkes@ecmwf.int .

Thanks for your patience.

**Comment by jameshawkes** [comment]
CLA signed successfully, thank you!

**Comment by shahramn** [comment]
This has now been merged to BitBucket and will appear in the next release of ecCodes. Many thanks

**Pull request merged**
