### PR TITLE
Add packingType for template 5.200 (Run length packing with level values)

### PR DESCRIPTION
**Pull request by noritada**
Hello,

Thank you for adding support for template 5.200.  I used HEAD in the repository and noticed that `packingType` was left as `unknown` in `grib_ls`, so I added it.

I named RLE's `packingType` after simple packing and complex packing, but if there is a naming convention and my naming is inappropriate, I would appreciate it if you could let me know.

```shellsession
% ./install/bin/grib_ls Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin
Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin
edition      centre       date         dataType     gridType     stepRange    typeOfLevel  level        shortName    packingType
2            rjtd         20160822     af           regular_ll   0            surface      0            unknown      unknown
2            rjtd         20160822     af           regular_ll   10           surface      0            unknown      unknown
2            rjtd         20160822     af           regular_ll   20           surface      0            unknown      unknown
2            rjtd         20160822     af           regular_ll   30           surface      0            unknown      unknown
2            rjtd         20160822     af           regular_ll   40           surface      0            unknown      unknown
2            rjtd         20160822     af           regular_ll   50           surface      0            unknown      unknown
2            rjtd         20160822     af           regular_ll   1            surface      0            unknown      unknown
7 of 7 messages in Z__C_RJTD_20160822020000_NOWC_GPV_Ggis10km_Pphw10_FH0000-0100_grib2.bin

7 of 7 total messages in 1 files
```

Note: templates used in the data above is 3.0, 4.0, and 5.200 (so local section 4 templates are not used).
You can download it from [JMA's GPV sample data page](https://www.data.jma.go.jp/developer/gpv_sample.html); the link text is "竜巻発生確度ナウキャスト" and the file name is `tornado.zip`.
(I have read [a comment](https://github.com/ecmwf/eccodes/pull/72#issuecomment-1397651242) in #72 and think you are looking for such a data.)

Many thanks!

### CODE REVIEW

**Comment by shahramn** [comment]
Thank you. I'm afraid I got lost on that Japanese page! could not find tornado.zip
Can you send me the exact URL which will allow me to download it?

**Comment by shahramn** [comment]
Dear @noritada 
Can you please sign the CLA (Contributor License Agreement). That is a required step before I can continue.
Many thanks

**Comment by noritada** [comment]
I hope I can be of help to you. Here is the exact URL of tornado.zip: https://www.data.jma.go.jp/developer/gpv_sample/tornado.zip

By the way, I think CLA check URL would be http://claassistant.ecmwf.int/ecmwf/eccodes?pullRequest=74, but my web browsers reports me connection reset (`ERR_CONNECTION_RESET`) to that URL now. I think it may be a server-side problem. I am waiting to recover from the problem...

**Comment by shahramn** [comment]
> I hope I can be of help to you. Here is the exact URL of tornado.zip: https://www.data.jma.go.jp/developer/gpv_sample/tornado.zip
> 
> By the way, I think CLA check URL would be http://claassistant.ecmwf.int/ecmwf/eccodes?pullRequest=74, but my web browsers reports me connection reset (`ERR_CONNECTION_RESET`) to that URL now. I think it may be a server-side problem. I am waiting to recover from the problem...

Regarding the CLA signing:
Please check this page which may be of some help:
https://confluence.ecmwf.int/display/SUP/ECMWF+software+on+GitHub

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=74) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=74) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eccodes?pullRequest=74) it.</sub>

**Comment by noritada** [comment]
@shahramn Thank you very much for waiting.
Now I am able to access to the CLA app and have signed the agreement!

**Pull request closed without merging**
