### PR TITLE
Remove redundant conditionals and an assignment.

### PR DESCRIPTION
**Pull request by shinji-s**
Breaking out of the while loop and falling through guarantees that 'gm' is NULL.
!c->multi_support is equivalent to prev==NULL.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=34) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eccodes?pullRequest=34) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eccodes?pullRequest=34) it.</sub>

**Comment by shahramn** [comment]
Can you please provide a test case that demonstrates the problem

**Comment by shinji-s** [comment]
There is no logical problem in the code.  Hence I can think of no appropriate test cases that demonstrate any problem. This PR is about code clarity.
* It does not make sense to assign a value to a local variable if the variable is not going to be referenced after the assignment.
* There is no point in checking a variable for a value if the value being held is known. The extra check potentially wastes cpu cycles and, more importantly, makes code difficult to comprehend.

**Comment by shinji-s** [comment]
Closing as this PR is superceded by https://github.com/ecmwf/eccodes/pull/51.

**Pull request closed without merging**
