### PR TITLE
WIP: Check file-size of test-data in tests

### PR DESCRIPTION
**Pull request by shinji-s**
I spent fair amount of time trying to diagnose cause of a few failed ctest cases. The culprit turned out to be incomplete 'test.grib1' file. (At another time, the culprit was syno_1.burf.num.ref) Since the file downloading performed by the ecbuild cmake rule attempts by default no retries and keeps partially downloaded files laying around, possibility of this happening to other developers is not slim. It is better to flag the problem explicitly rather than having tests mysteriously fail. Perhaps ECBUILD_DOWNLOAD_RETRIES parameter also need to be tweaked for more robust downloading.

### CODE REVIEW

**Comment by shinji-s** [comment]
A better solution would be to declare data downloading tests to be fixtures and make them check the file size. But I guess it would requires more laborious work and wider changes.

**Comment by shinji-s** [comment]
I'm looking into that solution. Please hold the merge for now.

**Comment by shinji-s** [comment]
```
if( ENABLE_EXTRA_TESTS )
    # Download all data files
    ecbuild_get_test_multidata( TARGET eccodes_download_gribs
                            NOCHECK
                            NAMES ${files_to_download} )
endif()
```
Integrity checking provided by the ecbuild is explicitly disabled by eccodes.
Why is it?

**Comment by shahramn** [comment]
> I'm looking into that solution. Please hold the merge for now.

I am on my holidays so no rush re merging. Take your time. And many thanks for all your good work. Much appreciated

**Comment by shinji-s** [comment]
Noted. Thank you for the follow up.  Please enjoy the rest of your holidays.

**Comment by shinji-s** [comment]
Closing in favor of https://github.com/ecmwf/eccodes/pull/41.

**Pull request closed without merging**
